import React, { useState } from "react";
import {
  Plus, Trash2, ChevronDown, ChevronUp, Eye, EyeOff,
  BookOpen, Code2, FileText, CheckSquare, RefreshCw, Image as ImageIcon, Loader2, Sparkles
} from "lucide-react";
import toast from "react-hot-toast";
import api from "../lib/api";

// ---------------------------------------------------------------------------
// Image Uploader Widget
// ---------------------------------------------------------------------------
function QuestionImageUploader({ imageUrl, onChange }) {
  const [uploading, setUploading] = useState(false);

  const handleImageUpload = async (e) => {
    const file = e.target.files?.[0];
    if (!file) return;
    if (!/image\/(jpeg|jpg|png)/i.test(file.type)) {
      toast.error("Only images (JPG, PNG) are allowed");
      return;
    }

    setUploading(true);
    const formData = new FormData();
    formData.append("image", file);

    try {
      const res = await api.post("/api/ai/upload-image", formData, {
        headers: { "Content-Type": "multipart/form-data" }
      });
      onChange(res.data.imageUrl);
      toast.success("Image attached successfully");
    } catch (err) {
      toast.error("Image upload failed");
    } finally {
      setUploading(false);
    }
  };

  return (
    <div className="space-y-2 mt-4 pt-4 border-t border-gray-150">
      <label className="text-[10px] font-bold text-gray-500 uppercase tracking-widest block">Question Image Attachment</label>
      {imageUrl ? (
        <div className="relative inline-block group">
          <img src={imageUrl} alt="Attached" className="max-h-48 rounded-xl border border-gray-200 shadow-sm object-cover" />
          <button
            onClick={() => onChange(null)}
            className="absolute top-2 right-2 p-1.5 bg-black/80 hover:bg-black text-white rounded-lg opacity-0 group-hover:opacity-100 transition-opacity"
            title="Remove image"
          >
            <Trash2 size={12} />
          </button>
        </div>
      ) : (
        <div className="flex items-center gap-3">
          <label className="flex items-center gap-1.5 px-3 py-2 bg-white hover:bg-gray-50 border border-gray-200 text-gray-700 rounded-xl text-[10px] font-bold transition-all cursor-pointer shadow-sm">
            {uploading ? <Loader2 size={11} className="animate-spin" /> : <ImageIcon size={11} />}
            {uploading ? "Uploading..." : "Attach Image"}
            <input type="file" accept="image/png, image/jpeg, image/jpg" className="hidden" onChange={handleImageUpload} disabled={uploading} />
          </label>
        </div>
      )}
    </div>
  );
}

// ---------------------------------------------------------------------------
// AI Refinement / Regeneration Input Widget
// ---------------------------------------------------------------------------
function QuestionRegenerator({ question, onUpdated, documentId, loading, setLoading }) {
  const [prompt, setPrompt] = useState("");
  const [mode, setMode] = useState("refine"); // "refine" | "generate"
  const [show, setShow] = useState(false);

  const handleApply = async () => {
    if (!prompt.trim()) return;
    setLoading(true);
    try {
      if (mode === "refine") {
        const res = await api.post("/api/ai/regenerate-question", {
          question,
          prompt: prompt.trim(),
          documentId: documentId || null
        }, {
          timeout: 120000 // 2 minutes timeout
        });
        onUpdated(res.data);
        toast.success("Question refined by AI");
      } else {
        const res = await api.post("/api/ai/generate-quiz", {
          prompt: prompt.trim(),
          numMcq: question.questionType === "mcq" ? 1 : 0,
          numDescriptive: question.questionType === "descriptive" ? 1 : 0,
          numCoding: question.questionType === "coding" ? 1 : 0,
          difficulty: "Medium",
          documentId: documentId || null
        }, {
          timeout: 180000 // 3 minutes timeout
        });

        const generatedQs = res.data.parsed?.questions || [];
        if (generatedQs.length > 0) {
          const newQ = generatedQs[0];
          onUpdated({
            ...newQ,
            marks: question.marks || (question.questionType === "coding" ? 10 : question.questionType === "descriptive" ? 5 : 1)
          });
          toast.success("Question generated by AI");
        } else {
          toast.error("AI did not return any questions. Try a different topic.");
        }
      }
      setPrompt("");
      setShow(false);
    } catch (err) {
      toast.error(err.response?.data?.message || err.response?.data?.error || "AI operation failed");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="mt-3">
      {!show ? (
        <div className="flex items-center gap-2">
          <button
            type="button"
            onClick={() => { setMode("refine"); setShow(true); }}
            className="flex items-center gap-1.5 px-3 py-1.5 bg-gray-50 hover:bg-gray-100 border border-gray-200 text-xs font-medium text-gray-600 rounded-lg transition-colors cursor-pointer"
          >
            <RefreshCw size={11} className="text-gray-400" /> Refine with AI
          </button>
          <button
            type="button"
            onClick={() => { setMode("generate"); setShow(true); }}
            className="flex items-center gap-1.5 px-3 py-1.5 bg-gray-50 hover:bg-gray-100 border border-gray-200 text-xs font-medium text-gray-600 rounded-lg transition-colors cursor-pointer"
          >
            <Sparkles size={11} className="text-gray-400" /> Use AI to Generate
          </button>
        </div>
      ) : (
        <div className="space-y-2 mt-2 bg-gray-50 border border-gray-200 p-3.5 rounded-xl">
          <div className="flex items-center justify-between">
            <span className="text-[10px] font-medium text-gray-500">
              {mode === "refine" ? "Instruct AI to rewrite this question" : `Generate a new ${question.questionType} question from topic`}
            </span>
            <button onClick={() => setShow(false)} className="text-[9px] text-gray-400 font-bold hover:text-black">Cancel</button>
          </div>
          <div className="flex gap-2">
            <input
              type="text"
              placeholder={mode === "refine" 
                ? "E.g. Make this question harder, use different names, add Python syntax..."
                : "E.g. Binary Search Tree search runtime, Docker isolation benefits, etc..."}
              className="flex-1 px-3 py-2 bg-white border border-gray-200 rounded-lg text-xs focus:outline-none focus:border-black text-gray-900"
              value={prompt}
              onChange={(e) => setPrompt(e.target.value)}
              onKeyDown={(e) => e.key === "Enter" && handleApply()}
            />
            <button
              onClick={handleApply}
              disabled={loading || !prompt.trim()}
              className="px-3 bg-black hover:bg-gray-900 text-white rounded-lg text-xs font-bold transition-all disabled:opacity-20 flex items-center justify-center min-w-[64px]"
            >
              {loading ? <Loader2 size={12} className="animate-spin" /> : "Apply"}
            </button>
          </div>
        </div>
      )}
    </div>
  );
}

// ---------------------------------------------------------------------------
// MCQ Question Editor
// ---------------------------------------------------------------------------
function McqEditor({ question, onChange, onDelete, documentId }) {
  const [open, setOpen] = useState(true);
  const [loading, setLoading] = useState(false);

  const updateOption = (idx, val) => {
    const opts = [...(question.options || ["", "", "", ""])];
    opts[idx] = val;
    onChange({ ...question, options: opts });
  };

  if (loading) {
    return (
      <div className="border border-gray-200 rounded-2xl bg-white shadow-sm p-6 space-y-4 animate-pulse">
        <div className="flex items-center justify-between border-b border-gray-100 pb-3">
          <div className="flex items-center gap-3">
            <div className="w-16 h-6 bg-gray-200 rounded-full" />
            <div className="w-48 h-5 bg-gray-200 rounded-lg" />
          </div>
          <div className="w-12 h-5 bg-gray-200 rounded-lg" />
        </div>
        <div className="space-y-3 pt-1">
          <div className="w-full h-12 bg-gray-100 rounded-xl" />
          <div className="space-y-2">
            <div className="w-full h-10 bg-gray-50 rounded-xl" />
            <div className="w-full h-10 bg-gray-50 rounded-xl" />
          </div>
          <div className="flex items-center gap-2 pt-2">
            <Loader2 className="w-3.5 h-3.5 text-black animate-spin" />
            <span className="text-[10px] font-black text-gray-500 uppercase tracking-widest">AI is rewriting question...</span>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="border border-gray-200 rounded-2xl overflow-hidden bg-white shadow-sm p-6 space-y-4">
      <div
        className="flex items-center justify-between cursor-pointer border-b border-gray-100 pb-3"
        onClick={() => setOpen((p) => !p)}
      >
        <div className="flex items-center gap-3">
          <span className="bg-gray-100 text-gray-800 border border-gray-200 text-[10px] font-black uppercase tracking-widest px-3 py-1 rounded-full">MCQ</span>
          <span className="text-sm font-bold text-gray-900 line-clamp-1">{question.questionText || "Untitled question"}</span>
        </div>
        <div className="flex items-center gap-3">
          <span className="text-xs text-gray-400 font-bold">{question.marks} pt{question.marks !== 1 ? "s" : ""}</span>
          <button onClick={(e) => { e.stopPropagation(); onDelete(); }} className="p-1.5 text-gray-400 hover:text-red-500 hover:bg-red-50 rounded-lg transition-all">
            <Trash2 size={14} />
          </button>
          {open ? <ChevronUp size={16} className="text-gray-450 text-gray-400" /> : <ChevronDown size={16} className="text-gray-400" />}
        </div>
      </div>

      {open && (
        <div className="space-y-4 pt-1">
          <div>
            <label className="text-[10px] font-bold text-gray-400 uppercase tracking-widest block mb-1.5">Question Content</label>
            <textarea
              className="w-full p-4 bg-white border border-gray-200 rounded-xl text-sm text-gray-900 resize-none focus:outline-none focus:border-black font-semibold leading-relaxed"
              rows={2}
              value={question.questionText}
              onChange={(e) => onChange({ ...question, questionText: e.target.value })}
            />
          </div>

          <div>
            <label className="text-[10px] font-bold text-gray-400 uppercase tracking-widest block mb-2">Options — select correct answer</label>
            <div className="space-y-2">
              {(question.options || ["", "", "", ""]).map((opt, idx) => (
                <div key={idx} className={`flex items-center gap-3 p-3 rounded-xl border transition-all cursor-pointer ${question.correctAns === idx ? "border-black bg-gray-50 shadow-sm" : "border-gray-200 bg-white hover:border-gray-300"}`}
                  onClick={() => onChange({ ...question, correctAns: idx })}>
                  <span className={`w-7 h-7 rounded-lg flex items-center justify-center text-xs font-black flex-shrink-0 ${question.correctAns === idx ? "bg-black text-white" : "bg-gray-150 bg-gray-100 text-gray-500"}`}>
                    {String.fromCharCode(65 + idx)}
                  </span>
                  <input
                    className="flex-1 text-xs bg-transparent outline-none text-gray-800 placeholder:text-gray-300"
                    placeholder={`Option ${String.fromCharCode(65 + idx)}`}
                    value={opt}
                    onClick={(e) => e.stopPropagation()}
                    onChange={(e) => updateOption(idx, e.target.value)}
                  />
                  {question.correctAns === idx && <CheckSquare size={14} className="text-black flex-shrink-0" />}
                </div>
              ))}
            </div>
          </div>

          <div className="flex items-center gap-4">
            <div className="flex items-center gap-2">
              <label className="text-[10px] font-bold text-gray-400 uppercase tracking-widest">Marks</label>
              <input type="number" min={1} max={100}
                className="w-16 p-2 bg-white border border-gray-200 rounded-lg text-xs text-center font-bold text-gray-800 focus:outline-none focus:border-black"
                value={question.marks}
                onChange={(e) => onChange({ ...question, marks: parseInt(e.target.value, 10) || 1 })}
              />
            </div>
            <div className="h-4 w-[1px] bg-gray-200" />
            <QuestionRegenerator question={question} onUpdated={onChange} documentId={documentId} loading={loading} setLoading={setLoading} />
          </div>

          <QuestionImageUploader imageUrl={question.imageUrl} onChange={(url) => onChange({ ...question, imageUrl: url })} />
        </div>
      )}
    </div>
  );
}

// ---------------------------------------------------------------------------
// Descriptive Question Editor
// ---------------------------------------------------------------------------
function DescriptiveEditor({ question, onChange, onDelete, documentId }) {
  const [open, setOpen] = useState(true);
  const [loading, setLoading] = useState(false);

  if (loading) {
    return (
      <div className="border border-gray-200 rounded-2xl bg-white shadow-sm p-6 space-y-4 animate-pulse">
        <div className="flex items-center justify-between border-b border-gray-100 pb-3">
          <div className="flex items-center gap-3">
            <div className="w-16 h-6 bg-gray-200 rounded-full" />
            <div className="w-48 h-5 bg-gray-200 rounded-lg" />
          </div>
          <div className="w-12 h-5 bg-gray-200 rounded-lg" />
        </div>
        <div className="space-y-3 pt-1">
          <div className="w-full h-12 bg-gray-100 rounded-xl" />
          <div className="w-full h-12 bg-gray-50 rounded-xl" />
          <div className="flex items-center gap-2 pt-2">
            <Loader2 className="w-3.5 h-3.5 text-black animate-spin" />
            <span className="text-[10px] font-black text-gray-500 uppercase tracking-widest">AI is rewriting question...</span>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="border border-gray-200 rounded-2xl overflow-hidden bg-white shadow-sm p-6 space-y-4">
      <div className="flex items-center justify-between cursor-pointer border-b border-gray-100 pb-3" onClick={() => setOpen((p) => !p)}>
        <div className="flex items-center gap-3">
          <span className="bg-gray-100 text-gray-800 border border-gray-200 text-[10px] font-black uppercase tracking-widest px-3 py-1 rounded-full">Descriptive</span>
          <span className="text-sm font-bold text-gray-900 line-clamp-1">{question.questionText || "Untitled question"}</span>
        </div>
        <div className="flex items-center gap-3">
          <span className="text-xs text-gray-400 font-bold">{question.marks} pt{question.marks !== 1 ? "s" : ""}</span>
          <button onClick={(e) => { e.stopPropagation(); onDelete(); }} className="p-1.5 text-gray-400 hover:text-red-500 hover:bg-red-50 rounded-lg transition-all">
            <Trash2 size={14} />
          </button>
          {open ? <ChevronUp size={16} className="text-gray-450 text-gray-400" /> : <ChevronDown size={16} className="text-gray-400" />}
        </div>
      </div>

      {open && (
        <div className="space-y-4 pt-1">
          <div>
            <label className="text-[10px] font-bold text-gray-400 uppercase tracking-widest block mb-1.5">Question Content</label>
            <textarea className="w-full p-4 bg-white border border-gray-200 rounded-xl text-sm text-gray-900 resize-none focus:outline-none focus:border-black font-semibold leading-relaxed" rows={3}
              value={question.questionText}
              onChange={(e) => onChange({ ...question, questionText: e.target.value })}
            />
          </div>
          <div>
            <label className="text-[10px] font-bold text-gray-400 uppercase tracking-widest block mb-1.5">Expected Answer Guide (AI Scoring Metric)</label>
            <textarea className="w-full p-4 bg-white border border-gray-200 rounded-xl text-xs text-gray-700 italic resize-none focus:outline-none focus:border-black font-medium leading-relaxed" rows={3}
              placeholder="List key concepts or points that must be covered..."
              value={question.descriptiveAnswer || ""}
              onChange={(e) => onChange({ ...question, descriptiveAnswer: e.target.value })}
            />
          </div>
          <div className="flex items-center gap-4">
            <div className="flex items-center gap-2">
              <label className="text-[10px] font-bold text-gray-400 uppercase tracking-widest">Marks</label>
              <input type="number" min={1} max={100}
                className="w-16 p-2 bg-white border border-gray-200 rounded-lg text-xs text-center font-bold text-gray-800 focus:outline-none focus:border-black"
                value={question.marks}
                onChange={(e) => onChange({ ...question, marks: parseInt(e.target.value, 10) || 1 })}
              />
            </div>
            <div className="h-4 w-[1px] bg-gray-200" />
            <QuestionRegenerator question={question} onUpdated={onChange} documentId={documentId} loading={loading} setLoading={setLoading} />
          </div>

          <QuestionImageUploader imageUrl={question.imageUrl} onChange={(url) => onChange({ ...question, imageUrl: url })} />
        </div>
      )}
    </div>
  );
}

// ---------------------------------------------------------------------------
// Coding Question Editor
// ---------------------------------------------------------------------------
function CodingEditor({ question, onChange, onDelete, documentId }) {
  const [open, setOpen] = useState(true);
  const [loading, setLoading] = useState(false);
  const testcases = question.testcases || [];

  const updateTestCase = (idx, field, val) => {
    const updated = testcases.map((tc, i) => i === idx ? { ...tc, [field]: val } : tc);
    onChange({ ...question, testcases: updated });
  };

  const addTestCase = () => {
    onChange({ ...question, testcases: [...testcases, { input: "", output: "", hidden: false }] });
  };

  const removeTestCase = (idx) => {
    onChange({ ...question, testcases: testcases.filter((_, i) => i !== idx) });
  };

  const toggleHidden = (idx) => {
    updateTestCase(idx, "hidden", !testcases[idx].hidden);
  };

  if (loading) {
    return (
      <div className="border border-gray-200 rounded-2xl bg-white shadow-sm p-6 space-y-4 animate-pulse">
        <div className="flex items-center justify-between border-b border-gray-100 pb-3">
          <div className="flex items-center gap-3">
            <div className="w-16 h-6 bg-gray-200 rounded-full" />
            <div className="w-48 h-5 bg-gray-200 rounded-lg" />
          </div>
          <div className="w-12 h-5 bg-gray-200 rounded-lg" />
        </div>
        <div className="space-y-3 pt-1">
          <div className="w-full h-12 bg-gray-100 rounded-xl" />
          <div className="w-full h-24 bg-gray-50 rounded-xl" />
          <div className="flex items-center gap-2 pt-2">
            <Loader2 className="w-3.5 h-3.5 text-black animate-spin" />
            <span className="text-[10px] font-black text-gray-500 uppercase tracking-widest">AI is rewriting question...</span>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="border border-gray-200 rounded-2xl overflow-hidden bg-white shadow-sm p-6 space-y-4">
      <div className="flex items-center justify-between cursor-pointer border-b border-gray-100 pb-3" onClick={() => setOpen((p) => !p)}>
        <div className="flex items-center gap-3">
          <span className="bg-gray-100 text-gray-800 border border-gray-200 text-[10px] font-black uppercase tracking-widest px-3 py-1 rounded-full">Coding</span>
          <span className="text-sm font-bold text-gray-900 line-clamp-1">{question.questionText || "Untitled question"}</span>
        </div>
        <div className="flex items-center gap-3">
          <span className="text-xs text-gray-400 font-bold">{testcases.length} test{testcases.length !== 1 ? "s" : ""} · {question.marks} pts</span>
          <button onClick={(e) => { e.stopPropagation(); onDelete(); }} className="p-1.5 text-gray-400 hover:text-red-500 hover:bg-red-50 rounded-lg transition-all">
            <Trash2 size={14} />
          </button>
          {open ? <ChevronUp size={16} className="text-gray-450 text-gray-405 text-gray-400" /> : <ChevronDown size={16} className="text-gray-400" />}
        </div>
      </div>

      {open && (
        <div className="space-y-4 pt-1">
          <div>
            <label className="text-[10px] font-bold text-gray-400 uppercase tracking-widest block mb-1.5">Problem Statement</label>
            <textarea className="w-full p-4 bg-white border border-gray-200 rounded-xl text-sm text-gray-800 resize-none focus:outline-none focus:border-black font-mono leading-relaxed" rows={3}
              value={question.questionText}
              onChange={(e) => onChange({ ...question, questionText: e.target.value })}
            />
          </div>

          <div>
            <div className="flex items-center justify-between mb-3 border-b border-gray-200 pb-2">
              <label className="text-[10px] font-bold text-gray-400 uppercase tracking-widest">Test Cases (Exactly 10 recommended)</label>
              <button onClick={addTestCase} className="flex items-center gap-1 text-[10px] font-bold text-black hover:text-gray-700 transition-colors">
                <Plus size={10} /> Add Test Case
              </button>
            </div>
            <div className="space-y-2.5 max-h-96 overflow-y-auto pr-1 light-scrollbar">
              {testcases.map((tc, idx) => (
                <div key={idx} className={`p-4 rounded-xl border bg-gray-50/50 ${tc.hidden ? "border-gray-300" : "border-gray-200"}`}>
                  <div className="flex items-center justify-between mb-2 border-b border-gray-100 pb-1">
                    <span className="text-[9px] font-black text-gray-455 text-gray-400 uppercase tracking-wider">Test {idx + 1}</span>
                    <div className="flex items-center gap-2">
                      <button
                        onClick={() => toggleHidden(idx)}
                        className={`flex items-center gap-1 text-[9px] font-bold px-2 py-0.5 rounded border transition-colors ${tc.hidden ? "border-black bg-black text-white" : "border-gray-200 text-gray-500 hover:border-gray-300 hover:text-gray-800"}`}
                        title={tc.hidden ? "Hidden from students" : "Visible to students"}
                      >
                        {tc.hidden ? <EyeOff size={9} /> : <Eye size={9} />}
                        {tc.hidden ? "Hidden" : "Visible"}
                      </button>
                      <button onClick={() => removeTestCase(idx)} className="p-1 text-gray-400 hover:text-red-500 hover:bg-red-50 rounded transition-all">
                        <Trash2 size={11} />
                      </button>
                    </div>
                  </div>
                  <div className="grid grid-cols-2 gap-3">
                    <div>
                      <label className="text-[8px] font-bold text-gray-400 uppercase tracking-widest block mb-1">Input</label>
                      <textarea className="w-full p-2.5 bg-white border border-gray-200 rounded-lg text-xs font-mono text-gray-800 resize-none focus:outline-none focus:border-black min-h-[48px]"
                        value={tc.input} onChange={(e) => updateTestCase(idx, "input", e.target.value)} />
                    </div>
                    <div>
                      <label className="text-[8px] font-bold text-gray-400 uppercase tracking-widest block mb-1">Expected Output</label>
                      <textarea className="w-full p-2.5 bg-white border border-gray-200 rounded-lg text-xs font-mono text-gray-800 resize-none focus:outline-none focus:border-black min-h-[48px]"
                        value={tc.output} onChange={(e) => updateTestCase(idx, "output", e.target.value)} />
                    </div>
                  </div>
                </div>
              ))}
              {testcases.length === 0 && (
                <div className="text-center py-6 text-xs text-gray-400 border border-dashed border-gray-200 rounded-xl bg-white">
                  No test cases defined.
                </div>
              )}
            </div>
          </div>

          <div className="flex items-center gap-4">
            <div className="flex items-center gap-2">
              <label className="text-[10px] font-bold text-gray-400 uppercase tracking-widest">Marks</label>
              <input type="number" min={1} max={100}
                className="w-16 p-2 bg-white border border-gray-200 rounded-lg text-xs text-center font-bold text-gray-800 focus:outline-none focus:border-black"
                value={question.marks}
                onChange={(e) => onChange({ ...question, marks: parseInt(e.target.value, 10) || 1 })}
              />
            </div>
            <div className="h-4 w-[1px] bg-gray-200" />
            <QuestionRegenerator question={question} onUpdated={onChange} documentId={documentId} loading={loading} setLoading={setLoading} />
          </div>

          <QuestionImageUploader imageUrl={question.imageUrl} onChange={(url) => onChange({ ...question, imageUrl: url })} />
        </div>
      )}
    </div>
  );
}

// ---------------------------------------------------------------------------
// Main AiQuizEditor export
// ---------------------------------------------------------------------------
export default function AiQuizEditor({ questions, onChange, documentId }) {
  const updateQuestion = (idx, updated) => {
    const next = [...questions];
    next[idx] = updated;
    onChange(next);
  };

  const deleteQuestion = (idx) => {
    onChange(questions.filter((_, i) => i !== idx));
  };

  const addQuestion = (type) => {
    const base = { questionText: "", questionType: type, marks: type === "coding" ? 10 : type === "descriptive" ? 5 : 1, imageUrl: null };
    if (type === "mcq") Object.assign(base, { options: ["", "", "", ""], correctAns: 0 });
    if (type === "descriptive") Object.assign(base, { descriptiveAnswer: "" });
    if (type === "coding") Object.assign(base, { testcases: [{ input: "", output: "", hidden: false }] });
    onChange([...questions, base]);
  };

  return (
    <div className="space-y-6">
      {/* Question list */}
      {questions.map((q, idx) => {
        const props = { key: idx, question: q, onChange: (u) => updateQuestion(idx, u), onDelete: () => deleteQuestion(idx), documentId };
        if (q.questionType === "mcq") return <McqEditor {...props} />;
        if (q.questionType === "descriptive") return <DescriptiveEditor {...props} />;
        if (q.questionType === "coding") return <CodingEditor {...props} />;
        return null;
      })}

      {questions.length === 0 && (
        <div className="text-center py-16 text-gray-400 border border-dashed border-gray-200 rounded-2xl bg-white shadow-sm">
          <FileText className="w-10 h-10 mx-auto mb-3 opacity-20" />
          <p className="text-sm font-semibold">No questions configured. Add questions below.</p>
        </div>
      )}

      {/* Add question buttons */}
      <div className="flex flex-wrap gap-2 pt-2 justify-center">
        <button onClick={() => addQuestion("mcq")} className="flex items-center gap-1.5 px-5 py-3 bg-white border border-gray-200 text-gray-700 hover:border-black hover:text-black rounded-xl text-xs font-bold transition-all shadow-sm">
          <BookOpen size={13} /> + MCQ Question
        </button>
        <button onClick={() => addQuestion("descriptive")} className="flex items-center gap-1.5 px-5 py-3 bg-white border border-gray-200 text-gray-700 hover:border-black hover:text-black rounded-xl text-xs font-bold transition-all shadow-sm">
          <FileText size={13} /> + Descriptive Question
        </button>
        <button onClick={() => addQuestion("coding")} className="flex items-center gap-1.5 px-5 py-3 bg-white border border-gray-200 text-gray-700 hover:border-black hover:text-black rounded-xl text-xs font-bold transition-all shadow-sm">
          <Code2 size={13} /> + Coding Question
        </button>
      </div>
    </div>
  );
}
